/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description API root endpoint
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all sessions
         * @description List all registry review sessions.
         *
         *     Returns a list of all sessions with their current status.
         *     Status is derived from workflow_progress to reflect actual progress.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create review session
         * @description Create a new registry review session.
         *
         *     This initializes a session with project metadata. Documents can be added later.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session details
         * @description Get detailed information about a specific session.
         *
         *     Returns complete session state including workflow progress and documents.
         *     Status is derived from workflow_progress to reflect actual progress.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete session
         * @description Delete a review session and all its data.
         *
         *     Permanently removes the session and all associated files.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List example projects
         * @description List available example projects for testing.
         *
         *     Returns a list of example projects that can be used to test the review workflow.
         */
        get: operations["list_examples_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover documents
         * @description Discover and classify all documents in the project.
         *
         *     Scans the project directory and classifies documents by type
         *     (monitoring plan, verification report, GIS data, etc.).
         */
        post: operations["discover_documents_sessions__session_id__discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Map requirements to documents
         * @description Map registry requirements to discovered documents.
         *
         *     Uses semantic matching to identify which documents address which
         *     checklist requirements.
         */
        post: operations["map_requirements_sessions__session_id__map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/mapping-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mapping status
         * @description Get current requirement mapping status.
         *
         *     Returns statistics about which requirements are mapped and coverage levels.
         */
        get: operations["get_mapping_status_sessions__session_id__mapping_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/mapping-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mapping matrix view
         * @description Get a visual matrix view of document-to-requirement mappings.
         *
         *     Returns a structured matrix showing which documents map to which requirements,
         *     with confidence indicators and status. Use this to review mappings before
         *     proceeding to evidence extraction.
         */
        get: operations["get_mapping_matrix_sessions__session_id__mapping_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/confirm-all-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm all mappings
         * @description Confirm all suggested mappings in bulk.
         *
         *     Use this after reviewing the mapping matrix to accept all agent suggestions.
         *     This marks all suggested mappings as confirmed and enables evidence extraction.
         */
        post: operations["confirm_all_mappings_sessions__session_id__confirm_all_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/conversion-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get PDF conversion status
         * @description Get PDF conversion status and progress.
         *
         *     Returns comprehensive status of dual-track PDF extraction:
         *     - Fast extraction (PyMuPDF): immediate, 75-90% quality
         *     - High-quality extraction (Marker): background, 100% quality
         *
         *     Includes progress percentages, ETAs, and per-document status.
         *     Use this to show users transparent progress during long conversions.
         */
        get: operations["get_conversion_status_sessions__session_id__conversion_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract evidence
         * @description Extract evidence for all requirements from mapped documents.
         *
         *     Analyzes documents and extracts specific evidence snippets with
         *     page citations for each requirement.
         */
        post: operations["extract_evidence_sessions__session_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/evidence-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get evidence matrix
         * @description Get structured evidence matrix for display.
         *
         *     USE THIS ENDPOINT when user asks for "evidence matrix" or "checklist".
         *     This is the primary endpoint for viewing extracted evidence.
         *
         *     Returns a standardized matrix with ALL columns:
         *     - requirement_id: Unique requirement identifier (e.g., REQ-001)
         *     - category: Requirement category (e.g., "Land Tenure")
         *     - status: Evidence status (covered/partial/missing)
         *     - confidence: Confidence score (0.0-1.0)
         *     - source_document: Document where evidence was found
         *     - page: Page number in source document
         *     - section: Section header where evidence appears
         *     - extracted_value: THE SPECIFIC VALUE for the registry checklist (e.g., "January 1, 2022", "Nicholas Denman")
         *     - validation_type: Type of validation (auto vs human judgment)
         *     - human_review_required: Whether human review is needed
         *
         *     IMPORTANT: Always display ALL columns including 'extracted_value' which contains
         *     the specific answer to enter in the registry checklist's "Submitted Material" column.
         */
        get: operations["get_evidence_matrix_sessions__session_id__evidence_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cross-validate evidence
         * @description Run cross-document validation checks.
         *
         *     Stage 5: Validates consistency across all extracted evidence:
         *     - Date alignment (sampling vs imagery dates within 120 days)
         *     - Land tenure consistency (owner names, areas across documents)
         *     - Project ID validation (consistent across all documents)
         *
         *     Returns validation results with pass/fail/warning status.
         */
        post: operations["cross_validate_sessions__session_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate review report
         * @description Generate complete review report.
         *
         *     Stage 6: Creates review report with:
         *     - Executive summary with coverage statistics
         *     - Per-requirement findings with evidence citations
         *     - Cross-validation results
         *     - Items flagged for human review
         *
         *     Args:
         *         format: Output format - "markdown", "json", or "checklist" (default: markdown)
         *                 "checklist" generates a populated registry submission form
         *
         *     Returns report generation result with path to saved file.
         *     For checklist format, includes download_url for direct file download.
         */
        post: operations["generate_report_sessions__session_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/report/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download report
         * @description Download the review report as Markdown.
         *
         *     Returns the report.md file for direct download.
         *     Generate the report first with POST /sessions/{session_id}/report?format=markdown
         */
        get: operations["download_report_sessions__session_id__report_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/checklist/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download checklist
         * @description Download the populated registry checklist.
         *
         *     Returns the checklist.md file for direct download.
         *     Generate the checklist first with POST /sessions/{session_id}/report?format=checklist
         */
        get: operations["download_checklist_sessions__session_id__checklist_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/checklist/download-docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download DOCX checklist
         * @description Download the populated registry checklist as a Word document.
         *
         *     Returns the checklist.docx file for direct download.
         *     Generate the checklist first with POST /sessions/{session_id}/report?format=docx
         *     System-generated text appears in blue.
         */
        get: operations["download_checklist_docx_sessions__session_id__checklist_download_docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/review-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get review status
         * @description Get human review status for requirements.
         *
         *     Returns overrides and annotations for all or specific requirements.
         */
        get: operations["get_review_status_sessions__session_id__review_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set requirement override
         * @description Set human override status for a requirement.
         *
         *     This allows the reviewer to override agent assessments with expert judgment.
         *     The override is recorded with timestamp and attribution.
         */
        post: operations["set_override_sessions__session_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/override/{requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear override
         * @description Clear an override for a requirement.
         *
         *     This removes the override status, reverting to agent assessment.
         */
        delete: operations["clear_override_sessions__session_id__override__requirement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/annotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add annotation
         * @description Add an annotation/note to a requirement.
         *
         *     Annotations are separate from overrides and allow the reviewer to
         *     capture observations, questions, or concerns without making a decision.
         */
        post: operations["add_annotation_sessions__session_id__annotation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/determination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get final determination
         * @description Get the final determination for a session.
         *
         *     Returns the current determination status and details.
         */
        get: operations["get_determination_sessions__session_id__determination_get"];
        put?: never;
        /**
         * Set final determination
         * @description Set the final determination for the review.
         *
         *     This is the official decision on whether the project should be approved,
         *     conditionally approved, rejected, or placed on hold.
         */
        post: operations["set_determination_sessions__session_id__determination_post"];
        /**
         * Clear determination
         * @description Clear the final determination.
         *
         *     This allows the determination to be reconsidered.
         */
        delete: operations["clear_determination_sessions__session_id__determination_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get revision requests
         * @description Get all revision requests for a session.
         *
         *     Returns a list of revision requests with summary statistics.
         */
        get: operations["get_revisions_sessions__session_id__revisions_get"];
        put?: never;
        /**
         * Request revision
         * @description Request revision from project proponent for a requirement.
         *
         *     Marks a requirement as pending proponent revision.
         */
        post: operations["request_revision_sessions__session_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/revisions/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get revision summary
         * @description Generate a summary of revision requests for the project proponent.
         *
         *     Returns a formatted markdown summary that can be shared.
         */
        get: operations["get_revision_summary_sessions__session_id__revisions_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/revisions/{requirement_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve revision
         * @description Mark a revision request as resolved.
         *
         *     Call this after receiving and processing revised documents.
         */
        post: operations["resolve_revision_sessions__session_id__revisions__requirement_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audit log
         * @description Get the audit log for a session.
         *
         *     Returns a chronological list of all actions taken during the review,
         *     with optional filtering by action type or actor.
         */
        get: operations["get_audit_log_sessions__session_id__audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/verify-extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify extraction
         * @description Record human verification of a specific evidence extraction.
         *
         *     Unlike requirement-level overrides, this allows verifying individual
         *     evidence snippets. Each snippet can be verified, rejected, or flagged.
         */
        post: operations["verify_extraction_sessions__session_id__verify_extraction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/verification-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get verification status
         * @description Get verification status for all or specific requirements.
         *
         *     Returns summary of how many snippets are verified/rejected/pending.
         */
        get: operations["get_verification_status_sessions__session_id__verification_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/resolve-coordinates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve PDF coordinates
         * @description Resolve PDF bounding box coordinates for evidence snippets.
         *
         *     Finds the exact location in the PDF where evidence text appears,
         *     enabling precise highlighting in the viewer.
         *
         *     Args:
         *         session_id: Session identifier
         *         snippet_id: Optional specific snippet to resolve
         *         requirement_id: Optional requirement to resolve all snippets for
         */
        post: operations["resolve_coordinates_sessions__session_id__resolve_coordinates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with AI agent
         * @description Conversational AI agent for the review workspace.
         *
         *     Receives user message plus context (focused requirement, visible document/page).
         *     Calls Claude API with session-aware tools.
         *     Returns response with proposed actions that the user can execute.
         *
         *     This is a human-in-the-loop design: the agent proposes actions, but the user
         *     must confirm before any action is executed.
         */
        post: operations["agent_chat_sessions__session_id__agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file to session
         * @description Upload a file to an existing session.
         *
         *     Accepts base64-encoded file content and adds it to the session's documents.
         *     Note: Session must have been created with documents (e.g., via /start-example-review
         *     or /start-review-with-files). Use /start-review-with-files for new reviews.
         */
        post: operations["upload_file_sessions__session_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/start-review-with-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start review with uploaded files
         * @description Start a new review by uploading files directly.
         *
         *     Creates a session, saves uploaded files, discovers documents, and begins processing.
         *     This is the primary endpoint for ChatGPT file uploads.
         *
         *     Files must be base64-encoded. Returns session details and discovery results.
         */
        post: operations["start_review_with_files_start_review_with_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/start-example-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start review with example project
         * @description Start a review using an example project.
         *
         *     Creates a new session with documents from an example project directory,
         *     then automatically discovers and classifies the documents.
         *
         *     Available examples: '22-23', '23-24' (crediting periods)
         */
        post: operations["start_example_review_start_example_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate-upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate secure upload URL
         * @description Generate a secure URL where the user can upload files directly.
         *
         *     This is Step 1 of the two-step upload pattern for ChatGPT integration.
         *     ChatGPT calls this endpoint, then instructs the user to click the URL
         *     and upload their files. After upload, call /process-upload/{upload_id}.
         */
        post: operations["generate_upload_url_generate_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * File upload form
         * @description Serve HTML form for file upload.
         *
         *     Users are directed here from ChatGPT to upload their files directly.
         */
        get: operations["upload_form_upload__upload_id__get"];
        put?: never;
        /**
         * Handle file upload
         * @description Handle direct file uploads from the browser form.
         *
         *     Files are saved and associated with the pending upload session.
         */
        post: operations["handle_file_upload_upload__upload_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process-upload/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process uploaded files
         * @description Process files after user uploads them via the upload URL.
         *
         *     This is Step 2 of the two-step upload pattern. ChatGPT calls this
         *     after the user confirms they uploaded files.
         */
        post: operations["process_uploaded_files_process_upload__upload_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload-status/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check upload status
         * @description Check the status of an upload session.
         */
        get: operations["check_upload_status_upload_status__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gdrive/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accessible Google Drive folders
         * @description List folders accessible to the service account.
         *
         *     Returns top-level folders that the service account has access to.
         *     These are typically folders explicitly shared with the service account.
         */
        get: operations["list_gdrive_folders_gdrive_folders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gdrive/folders/{folder_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files in a Google Drive folder
         * @description List files in a specific Google Drive folder.
         *
         *     Returns PDF files and subfolders within the specified folder.
         *     Only PDF files are returned as they are the supported document type.
         */
        get: operations["list_gdrive_folder_files_gdrive_folders__folder_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/import/gdrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import files from Google Drive
         * @description Import files from Google Drive to a session.
         *
         *     Downloads selected files from Google Drive and adds them to the session.
         *     After import, runs document discovery to process the new files.
         */
        post: operations["import_gdrive_files_sessions__session_id__import_gdrive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAnnotationRequest */
        AddAnnotationRequest: {
            /**
             * Requirement Id
             * @description Requirement ID (e.g., 'REQ-001')
             */
            requirement_id: string;
            /**
             * Note
             * @description The annotation text
             */
            note: string;
            /**
             * Annotation Type
             * @description Type: note, question, concern, clarification
             * @default note
             */
            annotation_type: string;
            /**
             * Reviewer
             * @description Identifier of the reviewer
             * @default user
             */
            reviewer: string;
        };
        /** AgentAction */
        AgentAction: {
            /**
             * Type
             * @description Action type: navigate, extract, validate, etc.
             */
            type: string;
            /**
             * Label
             * @description Button label for UI
             */
            label: string;
            /**
             * Params
             * @description Action parameters
             */
            params?: {
                [key: string]: unknown;
            };
        };
        /** AgentChatRequest */
        AgentChatRequest: {
            /**
             * Message
             * @description User message to the agent
             */
            message: string;
            /** @description Current workspace context */
            context?: components["schemas"]["AgentContext"] | null;
        };
        /** AgentChatResponse */
        AgentChatResponse: {
            /**
             * Message
             * @description Agent's text response
             */
            message: string;
            /**
             * Actions
             * @description Proposed actions as buttons
             */
            actions?: components["schemas"]["AgentAction"][];
            /**
             * Sources
             * @description Referenced documents/pages
             */
            sources?: components["schemas"]["AgentSource"][];
        };
        /** AgentContext */
        AgentContext: {
            /**
             * Focused Requirement Id
             * @description Currently focused requirement ID
             */
            focused_requirement_id?: string | null;
            /**
             * Visible Document Id
             * @description Currently visible document ID
             */
            visible_document_id?: string | null;
            /**
             * Visible Page
             * @description Currently visible page number
             */
            visible_page?: number | null;
        };
        /** AgentSource */
        AgentSource: {
            /**
             * Document Id
             * @description Document ID
             */
            document_id: string;
            /**
             * Document Name
             * @description Document filename
             */
            document_name: string;
            /**
             * Page
             * @description Page number
             */
            page?: number | null;
            /**
             * Text
             * @description Relevant excerpt
             */
            text?: string | null;
        };
        /** Body_handle_file_upload_upload__upload_id__post */
        Body_handle_file_upload_upload__upload_id__post: {
            /** Files */
            files: string[];
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Project Name
             * @description Name of the project to review
             */
            project_name: string;
            /**
             * Methodology
             * @description Methodology identifier (default: soil-carbon-v1.2.2)
             * @default soil-carbon-v1.2.2
             */
            methodology: string;
            /**
             * Project Id
             * @description Optional project ID (e.g., C06-4997)
             */
            project_id?: string | null;
        };
        /** GDriveImportRequest */
        GDriveImportRequest: {
            /**
             * Folder Id
             * @description Google Drive folder ID to import from
             */
            folder_id: string;
            /**
             * File Ids
             * @description List of file IDs to import
             */
            file_ids: string[];
        };
        /** GenerateUploadUrlRequest */
        GenerateUploadUrlRequest: {
            /**
             * Project Name
             * @description Name of the project to review
             */
            project_name: string;
            /**
             * Methodology
             * @description Methodology identifier
             * @default soil-carbon-v1.2.2
             */
            methodology: string;
            /**
             * Session Id
             * @description Existing session ID to add files to (optional)
             */
            session_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ResolveRevisionRequest */
        ResolveRevisionRequest: {
            /**
             * Resolution Notes
             * @description Notes about how the revision was resolved
             */
            resolution_notes: string;
            /**
             * Resolved By
             * @description Identifier of the resolver
             * @default user
             */
            resolved_by: string;
        };
        /** RevisionRequest */
        RevisionRequest: {
            /**
             * Requirement Id
             * @description Requirement ID (e.g., 'REQ-001')
             */
            requirement_id: string;
            /**
             * Description
             * @description What revision is needed from proponent
             */
            description: string;
            /**
             * Priority
             * @description Priority: critical, high, medium, low
             * @default medium
             */
            priority: string;
            /**
             * Requested By
             * @description Identifier of the requester
             * @default user
             */
            requested_by: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Project Name */
            project_name: string;
            /** Methodology */
            methodology: string;
            /** Created At */
            created_at: string;
            /** Requirements Total */
            requirements_total: number;
            /** Message */
            message: string;
        };
        /** SetDeterminationRequest */
        SetDeterminationRequest: {
            /**
             * Determination
             * @description Final decision: approve, conditional, reject, hold
             */
            determination: string;
            /**
             * Notes
             * @description Required explanation of the determination
             */
            notes: string;
            /**
             * Conditions
             * @description For conditional approvals
             */
            conditions?: string | null;
            /**
             * Reviewer
             * @description Identifier of the reviewer
             * @default user
             */
            reviewer: string;
        };
        /** SetOverrideRequest */
        SetOverrideRequest: {
            /**
             * Requirement Id
             * @description Requirement ID (e.g., 'REQ-001')
             */
            requirement_id: string;
            /**
             * Override Status
             * @description Decision status: approved, rejected, needs_revision, conditional, pending
             */
            override_status: string;
            /**
             * Notes
             * @description Optional notes explaining the decision
             */
            notes?: string | null;
            /**
             * Reviewer
             * @description Identifier of the reviewer
             * @default user
             */
            reviewer: string;
        };
        /** StartExampleReviewRequest */
        StartExampleReviewRequest: {
            /**
             * Example Name
             * @description Name of example project (e.g., '22-23')
             */
            example_name: string;
            /**
             * Project Name
             * @description Custom project name (optional)
             */
            project_name?: string | null;
        };
        /** StartReviewWithFilesRequest */
        StartReviewWithFilesRequest: {
            /**
             * Project Name
             * @description Name of the project to review
             */
            project_name: string;
            /**
             * Files
             * @description List of files to upload (base64 encoded)
             */
            files: components["schemas"]["UploadFileRequest"][];
            /**
             * Methodology
             * @description Methodology identifier
             * @default soil-carbon-v1.2.2
             */
            methodology: string;
        };
        /** UploadFileRequest */
        UploadFileRequest: {
            /**
             * Filename
             * @description Name of the file being uploaded
             */
            filename: string;
            /**
             * Content Base64
             * @description Base64-encoded file content
             */
            content_base64: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyExtractionRequest */
        VerifyExtractionRequest: {
            /**
             * Snippet Id
             * @description ID of the evidence snippet to verify
             */
            snippet_id: string;
            /**
             * Requirement Id
             * @description Requirement ID this snippet belongs to
             */
            requirement_id: string;
            /**
             * Status
             * @description Verification status: verified, rejected, partial, needs_context
             */
            status: string;
            /**
             * Notes
             * @description Reviewer notes
             */
            notes?: string | null;
            /**
             * Reviewer
             * @description Reviewer identifier
             * @default user
             */
            reviewer: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_examples_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discover_documents_sessions__session_id__discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_requirements_sessions__session_id__map_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mapping_status_sessions__session_id__mapping_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mapping_matrix_sessions__session_id__mapping_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_all_mappings_sessions__session_id__confirm_all_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversion_status_sessions__session_id__conversion_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_evidence_sessions__session_id__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_matrix_sessions__session_id__evidence_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cross_validate_sessions__session_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_sessions__session_id__report_post: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_sessions__session_id__report_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_checklist_sessions__session_id__checklist_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_checklist_docx_sessions__session_id__checklist_download_docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_status_sessions__session_id__review_status_get: {
        parameters: {
            query?: {
                requirement_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_override_sessions__session_id__override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_override_sessions__session_id__override__requirement_id__delete: {
        parameters: {
            query?: {
                reviewer?: string;
            };
            header?: never;
            path: {
                session_id: string;
                requirement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_annotation_sessions__session_id__annotation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAnnotationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_determination_sessions__session_id__determination_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_determination_sessions__session_id__determination_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDeterminationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_determination_sessions__session_id__determination_delete: {
        parameters: {
            query?: {
                reviewer?: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revisions_sessions__session_id__revisions_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_revision_sessions__session_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revision_summary_sessions__session_id__revisions_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_revision_sessions__session_id__revisions__requirement_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                requirement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_sessions__session_id__audit_log_get: {
        parameters: {
            query?: {
                action_filter?: string | null;
                actor_filter?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_extraction_sessions__session_id__verify_extraction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verification_status_sessions__session_id__verification_status_get: {
        parameters: {
            query?: {
                requirement_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_coordinates_sessions__session_id__resolve_coordinates_post: {
        parameters: {
            query?: {
                snippet_id?: string | null;
                requirement_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_chat_sessions__session_id__agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_sessions__session_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadFileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_review_with_files_start_review_with_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartReviewWithFilesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_example_review_start_example_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExampleReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_upload_url_generate_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_form_upload__upload_id__get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handle_file_upload_upload__upload_id__post: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_handle_file_upload_upload__upload_id__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_uploaded_files_process_upload__upload_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_upload_status_upload_status__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gdrive_folders_gdrive_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_gdrive_folder_files_gdrive_folders__folder_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_gdrive_files_sessions__session_id__import_gdrive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GDriveImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
